mlflow:
  tracking_uri: "sqlite:///mlflow.db"
  experiment_name: "movie-hit-flop-exp"

data:
  path: "data/popular_movies.csv"

model:
  genres:
    - Action
    - Adventure
    - Animation
    - Comedy
    - Crime
    - Documentary
    - Drama
    - Family
    - Fantasy
    - History
    - Horror
    - Music
    - Mystery
    - Romance
    - Science Fiction
    - TV Movie
    - Thriller
    - War
    - Western
  target: is_hit
